version: '3'
services:
  setup-mpc-server:
    build: .
    image: 278380418400.dkr.ecr.eu-west-2.amazonaws.com/setup-mpc-server
    command: yarn start
    environment:
      NODE_ENV: production
    ports:
      - '8081:80'
    volumes:
      - .:/usr/src/setup-mpc-server
      - ../setup-mpc-common:/usr/src/setup-mpc-server/node_modules/setup-mpc-common
